# Generated by Django 5.2.7 on 2025-10-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('experience_year', models.FloatField()),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('category', models.CharField(choices=[('maid', 'House Maid'), ('babysitter', 'Babysitter'), ('caregiver', 'Caregiver')], max_length=20)),
                ('contactNo', models.CharField(max_length=15)),
                ('hourlyRate', models.FloatField()),
                ('availability', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
